feature/authentication-api
Supershift/Sushi.Mediakiwi.UI pull request #9
Opened 2021-12-13 15:31 UTC by lui297

Changes:
- added an authenticationaction and mutation to store;
- added an authenticationresponsemodel;
- fixed the login connection on the view page;
- added an api builder for future environment variables.
- lint error hotfix

2021-12-14 14:30 UTC, jeanpaulkommers commented on vue.config.js
> +    host: '127.0.0.1',
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
    host: "127.0.0.1",
```

2021-12-14 15:51 UTC, jeanpaulkommers commented on vetur.config.js
> +    './src',
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
    "./src",
```

2021-12-14 15:51 UTC, jeanpaulkommers commented on vue.config.js
> +    host: '127.0.0.1',
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
    host: "127.0.0.1",
```

2021-12-16 08:21 UTC, jeanpaulkommers requested changes
Fix all linter errors
Maybe move the API calls like _getMediakiwiContentAPI_, _getTopNavigationAPI_, etc to the api.ts
the store is getting **very** big

2021-12-16 08:21 UTC, jeanpaulkommers commented on src/components/ResetPassword.vue
> +      console.log("email.value, validEmail.value");
No console log

2021-12-16 08:21 UTC, jeanpaulkommers commented on src/components/ResetPassword.vue
> +        console.log(customEmailInput.value.fieldValue);
no console log

2021-12-27 14:56 UTC, jeanpaulkommers commented on src/store/modules/Content/mutations.ts
> +  [MutationTypes.SET_POST_CONTENT](state: S, payload: PostContentMediakiwiResponseModel|any): void,
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
  [MutationTypes.SET_POST_CONTENT](state: S, payload: PostContentMediakiwiResponseModel|unknown): void,
```

2022-01-03 10:58 UTC, jeanpaulkommers commented on src/components/form/FormComponent.vue
> +                <div class="col"
Codacy has a fix for the issue: [Expected a linebreak before this attribute.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
              <div
```

2022-01-03 10:58 UTC, jeanpaulkommers commented on src/components/form/FormComponent.vue
> +                <div class="col-xl"
Codacy has a fix for the issue: [Expected a linebreak before this attribute.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
              <div
```

2022-01-06 13:36 UTC, jeanpaulkommers commented on src/components/form/FormComponent.vue
> +                <div class="col"
Codacy has a fix for the issue: [Expected a linebreak before this attribute.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
              <div
```

2022-01-06 13:36 UTC, jeanpaulkommers commented on src/components/form/FormComponent.vue
> +                <div class="col-xl"
Codacy has a fix for the issue: [Expected a linebreak before this attribute.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
              <div
```

2022-01-06 14:01 UTC, jeanpaulkommers commented on src/utils/api-service.ts
> +      axiosInstance.post<any>("content/PostContent", request, config)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
      axiosInstance.post<unknown>("content/PostContent", request, config)
```

2022-01-06 15:55 UTC, jeanpaulkommers commented on src/utils/api-service.ts
> +      axiosInstance.post<any>("content/PostContent", request, config)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
      axiosInstance.post<unknown>("content/PostContent", request, config)
```

2022-01-06 16:12 UTC, jeanpaulkommers commented on src/utils/api-service.ts
> +      axiosInstance.post<any>("content/PostContent", request, config)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
      axiosInstance.post<unknown>("content/PostContent", request, config)
```

2022-01-07 08:30 UTC, jeanpaulkommers commented on src/utils/api-service.ts
> +      axiosInstance.post<any>("content/PostContent", request, config)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
      axiosInstance.post<unknown>("content/PostContent", request, config)
```

2022-01-07 09:05 UTC, jeanpaulkommers commented on src/utils/api-service.ts
> +      axiosInstance.post<any>("content/PostContent", request, config)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
      axiosInstance.post<unknown>("content/PostContent", request, config)
```

2022-01-07 09:07 UTC, jeanpaulkommers commented on src/utils/api-service.ts
> +      axiosInstance.post<any>("content/PostContent", request, config)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
      axiosInstance.post<unknown>("content/PostContent", request, config)
```

2022-01-07 09:35 UTC, jeanpaulkommers commented on src/utils/api-service.ts
> +      axiosInstance.post<any>("content/PostContent", request, config)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
      axiosInstance.post<unknown>("content/PostContent", request, config)
```

2022-01-07 14:57 UTC, jeanpaulkommers commented on src/utils/api-service.ts
> +      axiosInstance.post<any>("content/PostContent", request, config)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/Supershift/Sushi.Mediakiwi.UI/pullRequest?prid=8560396)
```suggestion
      axiosInstance.post<unknown>("content/PostContent", request, config)
```

2022-01-10 16:02 UTC, jeanpaulkommers requested changes

2022-01-12 09:29 UTC, jonvanputten-sf approved these changes

2022-01-12 09:29 UTC, merged